$(document).ready(function(){
	ents.getProfileImage(ents.nick)
	.then(function(d){
		$('#profLabel').html(d+ents.nick);
	});
	ents.getProjectTotal.views.ByUsername(ents.nick)
	.then(function(d){
		$('#views').text(d);
	});
	ents.getProjectTotal.likes.ByUsername(ents.nick)
	.then(function(d){
		$('#likes').text(d);
	});
	ents.getProjectTotal.comments.ByUsername(ents.nick)
	.then(function(d){
		$('#comments').text(d);
	});
});